title: Andre Hanna
description: Hi! I’m Andre Hanna, a mechanical engineer with a passion for transforming complex concepts into practical solutions. I enjoy blending creativity with engineering precision, whether through advanced 3D modeling or hands-on experimentation. I’m constantly seeking new challenges that allow me to apply my technical expertise in meaningful ways across a variety of mechanical engineering roles.
show_downloads: false
theme: jekyll-theme-architect
